[versions]
agp = "8.4.2"
firebaseDatabaseKtx = "21.0.0"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
viewpager = "1.0.0"
zxingAndroidEmbedded = "4.3.0"

[libraries]
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
viewpager = { group = "androidx.viewpager", name = "viewpager", version.ref = "viewpager" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }